import { type NextPage } from "next";
import Head from "next/head";
import Main from "../modules/main";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>To Do List App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
};

export default Home;
